#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 25 14:47:13 2018

@author: zhangcheng
"""


class Bird:
    feather = True

    def __init__(self, age=1):
        self.age = age

    @property
    def leg_num(self):
        return self._leg_num

    @leg_num.setter
    def leg_num(self, v):
        self._leg_num = v

    def whatever(self):
        return 2

    eyes = property(fget=whatever)


if __name__ == '__main__':
    bird = Bird()
    bird.leg_num = 3
    bird.age = 10
    bird.feather = False
